version: "3.8"

services:
  webapp:
    image: quay.io/librasteve/harcstack-org:latest
    container_name: harcstack-org
    expose:
      - "3000"
    networks:
      - webnet
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy_proxy
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - webapp
    networks:
      - webnet
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

networks:
  webnet:
